defaults: &defaults
  app_name: "elele"
  foot_html: "&copy; elele."
  domain: "127.0.0.1:3000"    
  disqus_shortname: "elele"
  duoshuo_shortname: "elele"
  google_analytics_key: "UA-31513752-1"
  email_sender: 'elele.cool@gmail.com'
  twitter_id: "elele"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults