

# development:
#   sessions:
#     default:
#       database: elele_development
#         hosts:
#           - localhost:27017
# test:
#   sessions:
#     default:
#       database: elele_development
#         hosts:
#           - localhost:27017
# production:
#   sessions:
#     default:
#       database: elele_pro
#         hosts:
#           - localhost:27017
development:
  sessions:
    default:
      database: elele_development
      hosts:
        - localhost:27017