# config/mongo.yml

defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: elele-dev

test:
  <<: *defaults
  database: elele-test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: elele-pro
  # username:
  # password:
